### ISSUE TITLE
Won't let me select interface

### ISSUE THREAD

**Issue by D3C1PH3RM3** [raffaele-forte/backbox-anonymous#5]
Won't let me select wlano have checked airmon-ng used airodump everything is working the interface is named wlan0 when I type it in to select it says ether ether and does not do anything but repeat that line so I can't select an interface

[!] WARNING! It's a simple script that avoid the most common system data
    leaks. Your coumputer behaviour is the key to guarantee you a strong
    privacy protection and a good anonimate.

[i] Please edit /etc/default/backbox-anonymous with your custom values.

[i] Starting anonymous mode

 * Service  * Killed processes to prevent leaks
./anonymous: 264: ./anonymous: virt-what: not found

Do you want to change the MAC address? [Y/n] > Y
Select network interfaces [ether ether ether ether] > wlan0
Select network interfaces [ether ether ether ether] >

**Comment by indigopsy** [comment]
Are you sure you are using wlan0 ?
can you print me your ifconfig ?

**Comment by D3C1PH3RM3** [comment]
@indigopsy I will edit it and add in a few hours but off memory it says 

Wlan0 bc3 broadcam driver

**Comment by indigopsy** [comment]
Are you using sudo ?
On Friday, 25 March 2016, D3C1PH3RM3 <notifications@github.com> wrote:

> @indigopsy <https://github.com/indigopsy> I will edit it and add in a few
> hours but off memory it says
>
> Wlan0 bc3 broadcam driver
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/raffaele-forte/backbox-anonymous/issues/5#issuecomment-201348686>
>


-- 
-------------------------------------------------
La purga misma te enseña
ओं मणिपद्मे हूं
Free Tibet !

**Comment by D3C1PH3RM3** [comment]
@indigopsy yes I am using Kali Linux it is always at root user and its definitely wlan0 I tested it with airmon ng and wifite

**Comment by indigopsy** [comment]
I will install kali tonight
Will respond to you after I test it
:)

On Sunday, 27 March 2016, D3C1PH3RM3 <notifications@github.com> wrote:

> @indigopsy <https://github.com/indigopsy> yes I am using Kali Linux it is
> always at root user and its definitely wlan0 I tested it with airmon ng and
> wifite
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/raffaele-forte/backbox-anonymous/issues/5#issuecomment-202111104>
>


-- 
-------------------------------------------------
La purga misma te enseña
ओं मणिपद्मे हूं
Free Tibet !

**Comment by D3C1PH3RM3** [comment]
@indigopsy thank you sir! Many are having the same problem

**Comment by indigopsy** [comment]
@D3C1PH3RM3 
Finaly !!!

I found many differences between kali and backbox.
At least in command output.
I changed original code so it can work with Kali linux 2016-01
I tested it and it works.

[*] Install apps
`sudo apt-get install macchanger resolvconf curl tor`

[*] Edit torrc
`sudo nano  /etc/tor/torrc`

[*] Add this at bottom
``` 
VirtualAddrNetwork 10.192.0.0/10
TransPort 9040
DNSPort 53
AutomapHostsOnResolve 1
```

[*] Save file

[*] Start tor
`sudo service tor start`

[*] Check if tor is running ???
`sudo service tor status`

[*] Create new file
`sudo nano /etc/anonymous`

[*] Paste this code 
```
#!/bin/sh
#/bin/anonymous
#kali linux anonymous script
#indigopsy 2016-03-28 v.01

# sudo apt-get install macchanger resolvconf curl

NON_TOR="192.168.0.0/16 172.16.0.0/12"
TOR_UID="debian-tor"
TRANS_PORT="9040"
TO_KILL="chrome dropbox firefox pidgin skype thunderbird xchat qbittorrent remmina"
BLEACHBIT_CLEANERS="bash.history system.cache system.clipboard system.custom system.recent_documents system.rotated_logs system.tmp system.trash"
REAL_HOSTNAME="YOUR-PC-NAME"
DEVICE1="wlan0"
DEVICE2="eth0"
#DEVICE3=""


do_start() {
	service network-manager stop
	
	killall -q $TO_KILL
	
	change_mac
	
	change_hostname
	
	service tor stop
	service tor start
	
	redirect_to_tor	
	
	service network-manager start
}

do_stop() {
	service network-manager stop
	
	killall -q $TO_KILL
	
	service tor stop
	
	iptables_flush

	if [ -f /etc/network/iptables.rules ]; then
		iptables-restore < /etc/network/iptables.rules
		rm /etc/network/iptables.rules
	fi

	service resolvconf start

	change_mac
	
	this confises sysnaptic. I turned it off
	change_hostname $REAL_HOSTNAME	
	
	bleachbit -c $BLEACHBIT_CLEANERS >/dev/null
	
	service network-manager start
}

do_status() {
	#Kali hack
	ifconfig $DEVICE1 | grep ether | awk '{print " [$DEVICE1 MAC] " $2}'
	ifconfig $DEVICE2 | grep ether | awk '{print " [$DEVICE2 MAC] " $2}'
	
	
	#Backbox
	#ifconfig -a | grep $DEVICE1 | awk '{print " [$DEVICE1 MAC] " $1, $5}'
	#ifconfig -a | grep $DEVICE2 | awk '{print " [$DEVICE2 MAC] " $1, $5}'

	CURRENT_HOSTNAME=$(hostname)
	echo " [Hostname] $CURRENT_HOSTNAME"
	
	HTML=$(curl -s https://check.torproject.org/?lang=en_US)
	IP=$(echo "$HTML" | egrep -m1 -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')

	echo "$HTML" | grep -q "Congratulations. This browser is configured to use Tor."

	if [ $? -ne 0 ]; then
		echo " [IP] $IP"
		echo " [Tor] OFF\n"
		exit 3
	else
		echo " [IP] $IP"
		echo " [Tor] ON\n"
	fi
}

clean_dhcp() {
	dhclient -r
	rm -f /var/lib/dhcp/dhclient*
}

change_hostname() {
	clean_dhcp
	
	RANDOM_HOSTNAME=$(shuf -n 1 /etc/dictionaries-common/words | sed -r 's/[^a-zA-Z]//g' | awk '{print tolower($0)}')
	NEW_HOSTNAME=${1:-$RANDOM_HOSTNAME}

	echo "$NEW_HOSTNAME" > /etc/hostname
	sed -i 's/127.0.1.1.*/127.0.1.1\t'"$NEW_HOSTNAME"'/g' /etc/hosts

	service hostname start
	CURRENT_HOSTNAME=$(hostname)
	
	avahi-daemon --kill
}

change_mac() {
	macchanger -A $DEVICE1 && macchanger -A $DEVICE2 # && $DEVICE3
}

iptables_flush() {
	iptables -F
	iptables -t nat -F
}

redirect_to_tor() {
	# Kali doesn't have pid file ???
	#if [ ! -e /var/run/tor/tor.pid ]; then
	#	echo "\n[!] Tor is not running! Quitting...\n"
	#	exit 1
	#fi

	if ! [ -f /etc/network/iptables.rules ]; then
		iptables-save > /etc/network/iptables.rules
	fi

	iptables_flush

	service resolvconf stop

	echo 'nameserver 127.0.0.1' > /etc/resolv.conf

	iptables -t nat -A OUTPUT -m owner --uid-owner $TOR_UID -j RETURN
	iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports 53

	for NET in $NON_TOR 127.0.0.0/9 127.128.0.0/10; do
		iptables -t nat -A OUTPUT -d "$NET" -j RETURN
	done

	iptables -t nat -A OUTPUT -p tcp --syn -j REDIRECT --to-ports $TRANS_PORT
	iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

	for NET in $NON_TOR 127.0.0.0/8; do
		iptables -A OUTPUT -d "$NET" -j ACCEPT
	done

	iptables -A OUTPUT -m owner --uid-owner $TOR_UID -j ACCEPT
	iptables -A OUTPUT -j REJECT
}


case "$1" in
	start)
		do_start
	;;
	stop)
		do_stop
	;;
	status)
		do_status
	;;
	*)
		echo "Usage: $0 {start|stop|status}" >&2
		exit 3
	;;
esac

exit 0
```





[*] Save file

[*] Make executable
`sudo chmod +x /bin/anonymous`

[*] anonymous commands:
```
sudo anonymous start
sudo anonymous stop
sudo anonymous status
```

[*] Open web browser:
`https://check.torproject.org/`

**Comment by D3C1PH3RM3** [comment]
Thank you ! Your a genius @indigopsy I will close the issue when I get home thank you so much again

**Comment by D3C1PH3RM3** [comment]
Current MAC:   00:71:cc:8e:ed:85 (unknown)
Permanent MAC: 00:71:cc:8e:ed:85 (unknown)
New MAC:       00:23:e8:38:bd:e1 (Demco Corp.)
Current MAC:   08:9e:01:4f:fc:18 (QUANTA COMPUTER INC.)
Permanent MAC: 08:9e:01:4f:fc:18 (QUANTA COMPUTER INC.)
New MAC:       00:17:41:c8:06:f7 (DEFIDEV)
Failed to start hostname.service: Unit hostname.service is masked.
Failed to kill daemon: No such file or directory
./anon: 132: ./anon: cannot create /etc/resolv.conf: Directory nonexistent

is the erorr im now getting it just closes after that.
@indigopsy

**Comment by indigopsy** [comment]
I will try to test it again.
I'll send you the results tomorrow

On Wednesday, 30 March 2016, D3C1PH3RM3 <notifications@github.com> wrote:

> Current MAC: 00:71:cc:8e:ed:85 (unknown)
> Permanent MAC: 00:71:cc:8e:ed:85 (unknown)
> New MAC: 00:23:e8:38:bd:e1 (Demco Corp.)
> Current MAC: 08:9e:01:4f:fc:18 (QUANTA COMPUTER INC.)
> Permanent MAC: 08:9e:01:4f:fc:18 (QUANTA COMPUTER INC.)
> New MAC: 00:17:41:c8:06:f7 (DEFIDEV)
> Failed to start hostname.service: Unit hostname.service is masked.
> Failed to kill daemon: No such file or directory
> ./anon: 132: ./anon: cannot create /etc/resolv.conf: Directory nonexistent
>
> is the erorr im now getting it just closes after that.
> @indigopsy <https://github.com/indigopsy>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/raffaele-forte/backbox-anonymous/issues/5#issuecomment-203442038>
>


-- 
-------------------------------------------------
La purga misma te enseña
ओं मणिपद्मे हूं
Free Tibet !

**Comment by D3C1PH3RM3** [comment]
Any results? @indigopsy

**Comment by RustyHook** [comment]
/etc/resolv.conf is not a directory.

This script works after creating /etc/resolv.conf manually with "nameserver 127.0.0.1" in it.

then doing:

service resolvconf start
service network-manager restart

Also, I have to put my interfaces down manually, for mac change and hostname changes only after restart.

I would really like to edit the script with fixes, but I don't find myself skilled enough. I've never used bash and it would take time to study the script itself. I hope this info will somehow help you.

**Comment by D3C1PH3RM3** [comment]
@RustyHook @indigopsy  I had to do ifconfig wlan0 down to change Mac the script doesn't do it so you  have to do it manually so for all those that get Mac change error permission denied when running script do

ifconfig wlan0 down 

And I will do what rusty did and see if it works thanks for the revisions

**Comment by D3C1PH3RM3** [comment]
Current MAC:   00:71:cc:8e:ed:85 (unknown)
Permanent MAC: 00:71:cc:8e:ed:85 (unknown)
[ERROR] Could not change MAC: interface up or insufficient permissions: Device or resource busy
Failed to start hostname.service: Unit hostname.service is masked.
Failed to kill daemon: No such file or directory
./anon: 132: ./anon: cannot create /etc/resolv.conf: Directory nonexistent
root@consulates:/etc# echo "nameserver 127.0.0.1" | tee /etc/resolv.conf
tee: /etc/resolv.conf: No such file or directory
nameserver 127.0.0.1
root@consulates:/etc# service resolvconf start
root@consulates:/etc# service network-manager restart
root@consulates:/etc# ./anon start
Current MAC:   00:71:cc:8e:ed:85 (unknown)
Permanent MAC: 00:71:cc:8e:ed:85 (unknown)
[ERROR] Could not change MAC: interface up or insufficient permissions: Device or resource busy
Failed to start hostname.service: Unit hostname.service is masked.
Failed to kill daemon: No such file or directory
root@consulates:/etc# 

did not work and indigo is not responding I have lost hope in this script 
@indigopsy @RustyHook @raffaele-forte @4nto

**Comment by RustyHook** [comment]
ohh well, you were supposed to actually create /etc/resolv.conf first, sorry didn't mentione.

before echo|tee step, do touch /etc/resolv.conf then echo|tee command.

OR you can just simply create the file in your favorite editor and type it in, it doesn't really matter, this works too:

vim /etc/resolv.conf  


then type in nameserver ....

**Comment by D3C1PH3RM3** [comment]
I already have a resolve.conf when I try to edit it says something about a broken symlink I'll delete and replace with new one then @RustyHook

**Comment by D3C1PH3RM3** [comment]
Why can no one fix this does anyone know of another anonymous script to hide your activities online? @indigopsy @RustyHook @raffaele-forte @4nto

**Comment by RustyHook** [comment]
Maybe we have some real-life issues and don't have enough time to commit to this.
When I need to be anonymous on the network, the workaround I have provided you works for me.
To implement it in the script shouldn't be hard, it only takes some basic bash. BUT you would have to watch over the script and understand how it works like you are the one who made it. And then locate the issues and fix them.

Also, it says "backbox" in its name, which I assume means it is optimized for use on backbox linux, we are trying to run it in kali.

You could try fixing it too. Be the change which you wanna see, no?

**Comment by indigopsy** [comment]
[https://github.com/indigopsy/anonymous](https://github.com/indigopsy/anonymous)
