### ISSUE TITLE
Error: Mac Changer iz Missing

### ISSUE THREAD

**Issue by namandistro** [raffaele-forte/backbox-anonymous#6]
Their iz a error saying mac changer is missing so iz their any file missing or something is wrong?

**Comment by indigopsy** [comment]
Sudo apt-get install macchanger

On Wednesday, 23 March 2016, Naman Distro <notifications@github.com> wrote:

> Their iz a error saying mac changer is missing so iz their any file
> missing or something is wrong?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/raffaele-forte/backbox-anonymous/issues/6>
>


-- 
-------------------------------------------------
La purga misma te enseña
ओं मणिपद्मे हूं
Free Tibet !

**Comment by D3C1PH3RM3** [comment]
@indigopsy why was his question answered in 7 hours but mine has not been answered and its been 7 days??

**Comment by indigopsy** [comment]
I'm sorry mate. Didn't see it. After coffee I will answer to u

On Thursday, 24 March 2016, D3C1PH3RM3 <notifications@github.com> wrote:

> @indigopsy <https://github.com/indigopsy> why was his question answered
> in 7 hours but mine has not been answered and its been 7 days??
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/raffaele-forte/backbox-anonymous/issues/6#issuecomment-200614153>
>


-- 
-------------------------------------------------
La purga misma te enseña
ओं मणिपद्मे हूं
Free Tibet !

**Comment by namandistro** [comment]
@indigopsy Thanks!!!
BTW its a great peace of code.
